config/routes.rb
VideoStore::Application.routes.draw do

  root to: 'videos#index'
  resources :videos, only: [:show] do
    resources :purchases, only: [:new, :create]
  end

  resource :session

  resources :users, only: [:new, :create]

  namespace :admin do
    root to: 'dashboard#show'
    resources :videos
    resources :users, only: [:index, :update]
  end
end

app/models/purchase.rb
class Purchase < ActiveRecord::Base
  attr_accessible :user_id, :video_id

  belongs_to :user
  belongs_to :video

  validates_presence_of :user, :video

  after_create :send_notification_email

  def send_notification_email
    CustomerMailer.purchase_notification(self).deliver
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name, :password, :password_confirmation

  has_secure_password

  validates_presence_of :name, :email
  validates_uniqueness_of :email
  validates_presence_of :password, on: :create

  has_many :purchases
  has_many :videos, through: :purchases

  def owns?(video)
    return true if self.admin?
    return videos.include?(video)
  end
end

app/models/video.rb
class Video < ActiveRecord::Base
  attr_accessible :name, :slug, :video, :preview, :publication_date, :price, :price_cents
  has_attached_file :video
  has_attached_file :preview, styles: {
    thumb: '100x100#',
    full: '640x480#'
  }

  validates_presence_of :name, :slug, :publication_date, :video, :preview, :price

  monetize :price_cents

  has_many :purchases

  default_scope order('created_at DESC')

  def to_param
    slug
  end
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_filter :require_admin!
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::BaseController
  def show
    @videos = Video.all
  end
end

app/controllers/admin/videos_controller.rb
class Admin::VideosController < Admin::BaseController

  before_filter :find_video, only: [:edit, :update, :destroy]

  def new
    @video = Video.new
  end

  def create
    @video = Video.new(params[:video])
    if @video.save
      redirect_to admin_root_url, notice: 'Video Created'
    else
      render action: :new
    end
  end

  def edit
  end

  def update
    if @video.update_attributes(params[:video])
      redirect_to admin_root_url, notice: 'Video Updated'
    else
      render action: 'edit'
    end
  end

  def destroy
    @video.destroy
    redirect_to admin_root_url, notice: 'Video Deleted'
  end

  protected
  
  def find_video
    @video = Video.find_by_slug!(params[:id])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_user
  def current_user
    if session[:user_id].present?
      @current_user ||= User.includes(:videos).find(session[:user_id])
    end
  end

  def authenticate_user!
    unless current_user
      redirect_to new_session_url, notice: "Please log in to continue."
    end
  end

  def require_admin!
    authenticate_user!
    unless current_user.admin?
      redirect_to root_url
    end
  end

end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  before_filter :authenticate_user!
  before_filter :find_video

  def new
    @purchase = Purchase.new
    @purchase.video = @video
  end

  def create
    Stripe.api_key = 'MLqyzl8wv0Yxq26bQ82Baqi7fEaif3GY'

    token = params[:stripeToken]

    begin
      charge = Stripe::Charge.create(
        amount: @video.price_cents,
        currency: "usd",
        card: token,
        description: current_user.email
      )
      @purchase = Purchase.new(params[:purchase])
      @purchase.amount_cents = @video.price_cents
      @purchase.user = current_user
      @purchase.video = @video
      if @purchase.save
        redirect_to video_url(@video), notice: 'Thank you for your purchase!'
      else
        render action: "new"
      end
    rescue
      flash.now[:error] = "There was a problem charging your card."
      render action: "new"
    end
  end

  protected

  def find_video
    @video = Video.find_by_slug!(params[:video_id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user and user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:notice] = 'Welcome Back!'
      if session[:next_url].present?
        redirect_to session[:next_url]
      else
        redirect_to root_url
      end
    else
      flash.now.alert = "Invalid Email or Password"
      render action: 'new'
    end
  end

  def destroy
    reset_session
    redirect_to root_url, notice: 'You have been logged out.'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      session[:user_id] = @user.id
      if session[:next_url].present?
        redirect_to session[:next_url]
      else
        redirect_to root_url
      end
    else
      render action: 'new'
    end
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController

  before_filter :find_video, only: :show
  before_filter :ensure_ownership, only: :show

  def index
    @videos = Video.all
  end

  def show
  end

  protected 

  def find_video
    @video = VideoDecorator.find_by_slug!(params[:id])
  end

  def ensure_ownership
    if current_user.present?
      unless current_user.owns?(@video)
        redirect_to new_video_purchase_url(@video)
      end
    else
      session[:next_url] = video_url(params[:id])
      flash[:notice] = "Please log in or sign up to continue."
      redirect_to new_session_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/dashboard/show.html.erb
<h1>Admin Dashboard</h1>

<h3>Video Stats
  <%= link_to 'Add Video', new_admin_video_url, class: 'btn btn-primary', style: 'float: right' %>
</h3>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Publication Date</th>
      <th>Price</th>
      <th>Purchases</th>
      <th>Revenue Generated</th>
      <th>Management</th>
    </tr>
  </thead>
  <tbody>
    <% @videos.each do |video| 
      vid = VideoDecorator.decorate(video)
  %>
    <tr>
      <td><%= vid.link %></td>
      <td><%= vid.publication %></td>
      <td><%= vid.price %></td>
      <td><%= vid.purchases.count %></td>
      <td><%= vid.revenue %></td>
      <td>
        <%= link_to 'Edit', edit_admin_video_url(video) %> | 
        <%= link_to 'Delete', admin_video_url(video), method: :delete, confirm: 'Are you sure?' %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/admin/videos/_form.html.erb
<%= form_for @video, url: [:admin, @video] do |f| %>
  <% if @video.errors.any? %>
    <div class="alert alert-error">
      <h4>Whoops! There were problems with this video</h4>
      <ul>
        <% @video.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :slug %>
  <%= f.text_field :slug %>

  <%= f.label :publication_date %>
  <%= f.date_select :publication_date %>

  <%= f.label :price %>
  <%= f.text_field :price %>

  <%= f.label :video %>
  <%= f.file_field :video %>

  <%= f.label :preview, 'Preview Image' %>
  <%= f.file_field :preview %>

  <p>
    <%= f.submit class: 'btn btn-primary' %>
  </p>
<% end %>

app/views/admin/videos/edit.html.erb
<h1>Edit Video</h1>

<%= render partial: 'form' %>

app/views/admin/videos/new.html.erb
<h1>Add a Video</h1>

<%= render partial: 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VideoStore</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <script type="text/javascript" src="https://js.stripe.com/v2/"></script>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container">
    <div class="navbar">
      <div class="navbar-inner">
        <%= link_to 'Video Store', root_url, class: 'brand' %>
        <ul class="nav">
          <li><%= link_to 'Home', root_url %></li>
          <% if current_user %>
            <% if current_user.admin? %>
              <li>
                <%= link_to 'Admin Section', admin_root_url %>
              </li>
            <% end %>
            <li>
              <%= link_to 'Log Out', session_url, method: :delete %>
            </li>
          <% else %>
            <li>
              <%= link_to 'Log In', new_session_url %>
            </li>
            <li>
              <%= link_to 'Sign Up', new_user_url %>
            </li>
          <% end %>
        </ul>
      </div>
  </div>

  <div id="alert-block">
    <% flash.each do |type, message| %>
      <div class="alert" data-alert="alert">
        <a class="close" data-dismiss="alert" href="#">×</a>
        <%= message %>
      </div>
    <% end %>
  </div>

  <div class="container">
    <%= yield %>
  </div>

</body>
</html>

app/views/purchases/_form.html.erb
<%= form_for @purchase, url: [@video, @purchase] do |f| %>
  <% if @purchase.errors.any? %>
    <div class="alert alert-error">
      <h4>Whoops! We couldn't complete your purchase.</h4>
      <ul>
        <% @purchase.errors.full_messages.each do |message| %>
          <li><%= message %>
        <% end %>
      </ul>
    </div>
  <% end %>
  <span class="payment-errors error"></span>

  <label for="number">Credit Card Number</label>
  <input id="number" data-stripe="number" type="text" size="20" />

  <label for="cvc">CVC</label>
  <input id="cvc" type="text" data-stripe="cvc" />

  <label for="expiration">Expiration (MM/YYYY)</label>
  <input type="text" size="2" data-stripe="exp-month" />
  <span> / </span>
  <input type="text" size="4" data-stripe="exp-year" />

  <p>
    <%= f.submit 'Purchase Video', id: 'purchase-button', class: 'btn btn-primary' %>
  </p>
<% end %>

<script type="text/javascript">
  Stripe.setPublishableKey('pk_b9niDnYnuTF5nqnGjCwuFC0AkV4Gl');

  stripeResponseHandler = function(status, response) {
    var $form = $('#new_purchase');
    if (response.error) {
      $form.find('.payment-errors').text(response.error.message);
      $form.find('#purchase-button').prop('disabled', false);
    } else {
      var token = response.id;
      $form.append($('<input type="hidden" name="stripeToken" />').val(token));
      $form.get('0').submit();
    }
  }

  $('#new_purchase').submit(function(event) {
      var $form = $(this);
      $form.find('#purchase-button').prop('disabled', true);
      Stripe.createToken($form, stripeResponseHandler);
      return false;
  })
</script>

app/views/purchases/new.html.erb
<h1>Buy <%= @video.name %></h1>

<h3>Purchase Price: <%= @video.price.format %></h3>

<%= render partial: 'form' %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="alert alert-error">
      <h4>Whoops! There were problems with your signup.</h4>
      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.text_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>


  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <p>
    <%= f.submit 'Sign Up!' %>
  </p>

<% end %>

app/views/users/new.html.erb
<h1>Sign Up!</h1>

<%= render partial: 'form' %>

app/views/videos/_list_item.html.erb
<% video = VideoDecorator.decorate(list_item) %>

<div class="row">
  <div class="span2">
    <%= video.thumbnail %>
  </div>
  <div class="span8">
    <h3><%= video.link %></h3>
    <p>Published: <%= video.publication %><br /> Price: <%= video.price.format %></p>
  </div>
  <div class="span2">
    <%= video.link_button %>
    <%= video.edit_button %>
  </div>
</div>

app/views/videos/index.html.erb
<%= render partial: 'list_item', collection: @videos %>

app/views/videos/show.html.erb
<h1><%= @video.name %></h1>

<video width="640" height="480" controls>
  <source src="<%= @video.video.url %>" type="video/mp4">
  <object data="<%= @video.video.url %>" width="640" height="480">
  </object>
</video>